SHOWOFF_VERSION = '0.24.0'
REQUIRED_GEMS = %w(redcarpet showoff sinatra-websocket thin)

def create_file_if_needed(filename, force)
  File.open(filename, 'w+') do |f|
    yield f
  end
  true
end

def create_gems_file(filename, password, force, formatter, header=nil)
  create_file_if_needed(filename, force) do |file|
    file.puts header.call unless header.nil?
    file.puts "# Generated by Showoff v#{SHOWOFF_VERSION}"
    file.puts "# Using new modular architecture"

    # Format showoff gem with version constraint
    file.puts formatter.call('showoff', "~> #{SHOWOFF_VERSION}")

    # Add other required gems
    (REQUIRED_GEMS - ['showoff']).each { |gem| file.puts formatter.call(gem) }
    file.puts formatter.call("rack") if password
  end
end

create_gems_file('Gemfile', 
                false, 
                true, 
                lambda{ |gem, version=nil| version ? "gem '#{gem}', '#{version}'" : "gem '#{gem}'" },
                lambda{ "source 'https://rubygems.org'" })
