require 'spec_helper'
require 'tempfile'
require 'json'
require 'showoff_utils'

RSpec.describe ShowoffUtils do
  describe '.create_gems_file' do
    it 'writes Gemfile entries with version requirement and password rack when needed' do
      Dir.mktmpdir do |dir|
        path = File.join(dir, 'Gemfile')
        formatter = ->(gem, version=nil) { version ? "gem '#{gem}', '#{version}'" : "gem '#{gem}'" }
        header = -> { "source 'https://rubygems.org'" }

        created = described_class.create_gems_file(path, true, false, formatter, header)
        expect(created).to be true
        content = File.read(path)
        expect(content).to include("source 'https://rubygems.org'")
        expect(content).to include("Generated by Showoff v")
        expect(content).to match(/gem 'showoff', '~> \d+\.\d+\.\d+'/)
        expect(content).to include("gem 'redcarpet'")
        expect(content).to include("gem 'faye-websocket'")
        expect(content).to include("gem 'eventmachine'")
        expect(content).to include("gem 'rack'")
      end
    end

    it 'does not overwrite existing file unless force is true' do
      Dir.mktmpdir do |dir|
        path = File.join(dir, 'Gemfile')
        File.write(path, 'original')
        formatter = ->(gem, version=nil) { version ? "gem '#{gem}', '#{version}'" : "gem '#{gem}'" }

        created = described_class.create_gems_file(path, false, false, formatter)
        expect(created).to be false
        expect(File.read(path)).to eq('original')

        created2 = described_class.create_gems_file(path, false, true, formatter)
        expect(created2).to be true
        expect(File.read(path)).to include('Generated by Showoff')
      end
    end
  end
end
