# Generated by Showoff v0.24.0
# Using new modular architecture
require "showoff_ng"
require "showoff/server"
require "rack"
showoff_app = Showoff::Server.new
protected_showoff = Rack::Auth::Basic.new(showoff_app) do |username, password|
	password == 'mypassword'
end
run protected_showoff
